// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEfyHqVS4vRHNiK7wgg-ZUJzmDH6D-vuA',
    appId: '1:1018494190842:web:f38a2fb96d485926cef543',
    messagingSenderId: '1018494190842',
    projectId: 'livro-de-receitas-dbe9e',
    authDomain: 'livro-de-receitas-dbe9e.firebaseapp.com',
    storageBucket: 'livro-de-receitas-dbe9e.firebasestorage.app',
    measurementId: 'G-Y2QLGE0LBV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLNb03JUSYumZYGsJy6_HOrTFnzZoKcR0',
    appId: '1:1018494190842:android:91f2c2532f9aa7f3cef543',
    messagingSenderId: '1018494190842',
    projectId: 'livro-de-receitas-dbe9e',
    storageBucket: 'livro-de-receitas-dbe9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdjbW9A9-rXAlvWs-FqvHJyCPgmPj4nDA',
    appId: '1:1018494190842:ios:d182d57c5cde5dc9cef543',
    messagingSenderId: '1018494190842',
    projectId: 'livro-de-receitas-dbe9e',
    storageBucket: 'livro-de-receitas-dbe9e.firebasestorage.app',
    iosBundleId: 'br.com.CaioCorporation.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdjbW9A9-rXAlvWs-FqvHJyCPgmPj4nDA',
    appId: '1:1018494190842:ios:d182d57c5cde5dc9cef543',
    messagingSenderId: '1018494190842',
    projectId: 'livro-de-receitas-dbe9e',
    storageBucket: 'livro-de-receitas-dbe9e.firebasestorage.app',
    iosBundleId: 'br.com.CaioCorporation.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEfyHqVS4vRHNiK7wgg-ZUJzmDH6D-vuA',
    appId: '1:1018494190842:web:db2021ea3bee0a56cef543',
    messagingSenderId: '1018494190842',
    projectId: 'livro-de-receitas-dbe9e',
    authDomain: 'livro-de-receitas-dbe9e.firebaseapp.com',
    storageBucket: 'livro-de-receitas-dbe9e.firebasestorage.app',
    measurementId: 'G-JH43GWLJFZ',
  );
}
