// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;



/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZz7DugpwrbX4DYdJ6m3IpXlVb_J-0K4w',
    appId: '1:402258630979:web:c8e8d09aedaa7ebcbb37f6',
    messagingSenderId: '402258630979',
    projectId: 'jogo-forca-ddm',
    authDomain: 'jogo-forca-ddm.firebaseapp.com',
    storageBucket: 'jogo-forca-ddm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDo6o5F-3Xaw68P3IXwo6C7B2h2TrFlQE',
    appId: '1:402258630979:android:c6f18dbb03ab41cebb37f6',
    messagingSenderId: '402258630979',
    projectId: 'jogo-forca-ddm',
    storageBucket: 'jogo-forca-ddm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC1EboztyqTbTxetHIBLqTtBXrF7bm7Ng',
    appId: '1:402258630979:ios:c03751799116796dbb37f6',
    messagingSenderId: '402258630979',
    projectId: 'jogo-forca-ddm',
    storageBucket: 'jogo-forca-ddm.firebasestorage.app',
    iosBundleId: 'br.com.CaioCorporation.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC1EboztyqTbTxetHIBLqTtBXrF7bm7Ng',
    appId: '1:402258630979:ios:c03751799116796dbb37f6',
    messagingSenderId: '402258630979',
    projectId: 'jogo-forca-ddm',
    storageBucket: 'jogo-forca-ddm.firebasestorage.app',
    iosBundleId: 'br.com.CaioCorporation.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZz7DugpwrbX4DYdJ6m3IpXlVb_J-0K4w',
    appId: '1:402258630979:web:19207b33e912b7cebb37f6',
    messagingSenderId: '402258630979',
    projectId: 'jogo-forca-ddm',
    authDomain: 'jogo-forca-ddm.firebaseapp.com',
    storageBucket: 'jogo-forca-ddm.firebasestorage.app',
  );
}
